### ISSUE TITLE
Numpy's sqrt should be used on arrays, not single numbers

### ISSUE THREAD

**Issue by bicobus** [RedFT/Hexy#19]
numpy's design is to work with arrays and carries that much overhead, that is numpy needs to detect whether the argument is an array or an integer.

A quick benchmark shows that, for single numbers, `math.sqrt` is faster, but `numpy.sqrt` is a lot faster when dealing with arrays. If I'm not too tired, I see a factor of 10. Sadly many places within  <https://github.com/RedFT/Hexy/blob/1057e5df5962627c52c5bf92742ebc94204a6b9d/hexy/hexy.py> uses numpy's function on simple integers, including my recent contributions which were based on existing code.

```py
In [1]: import math

In [2]: import numpy as np

In [3]: %%timeit N = 10000
   ...: for i in range(N):
   ...:     z = math.sqrt(i)
   ...: 
1.45 ms ± 25.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [4]: %%timeit N = 10000
   ...: for i in range(N):
   ...:     z = np.sqrt(i)
   ...: 
16.8 ms ± 103 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [5]: %%timeit R = [i for i in range(10000)]
   ...: np.sqrt(R)
870 µs ± 981 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by RedFT** [comment]
There are three places where numpy's sqrt is used. 
https://github.com/RedFT/Hexy/search?q=sqrt

Two of the usages are in a line executed only once. 
https://github.com/RedFT/Hexy/blob/1057e5df5962627c52c5bf92742ebc94204a6b9d/hexy/hexy.py#L5

The third is in your contribution.
https://github.com/RedFT/Hexy/blob/1057e5df5962627c52c5bf92742ebc94204a6b9d/hexy/hexy.py#L46

**Comment by RedFT** [comment]
https://github.com/RedFT/Hexy/pull/20

**Comment by bicobus** [comment]
Thanks. I meant to do a PR but got otherwise occupied. Had I known it was this simple though...
