### ISSUE TITLE
Consider distributing your library on PyPI (pip)

### ISSUE THREAD

**Issue by breznak** [RedFT/Hexy#3]
Hi, 
first of all, this is a very nice software, thank you! :+1: 
We are going to use your lib in our oss library too, 
it would be great if you could package your lib in PyPI so it can be easily installed with 
`pip install hexy`

Cheers,

**Comment by RedFT** [comment]
You're absolutely welcome!

`pip install hexy` will now work. Try it out 👍

**Comment by breznak** [comment]
> pip install hexy will now work. Try it out +1

wow, you're amazing! Thank you :trophy:
