### ISSUE TITLE
Consider splitting dependencies to required, extras

### ISSUE THREAD

**Issue by breznak** [RedFT/Hexy#4]
The install with pip works perfectly :ok_hand: , one issue we're running into is the number of dependencies. 

We develop a library, and use hexy as well as a library for its work with coordinates, hex cells. 
Not being the end-user, we don't need any of the graphical stuff. 

I figured there's an option in `setup.py` to split dependencies to "required" and several named "extras" 
https://stackoverflow.com/questions/41678951/ignoring-some-requirements-when-installing-pip-requirements 

- core: 
for hexy.py, we found only numpy suffices (maybe some more for the tests?) 

- visualizations:
pull the large `game` and maybe some more. 

Would you consider splitting your setup to the 
- base library `pip install hexy`
- and providing extras? for example:
  - tests: `pip install hexy[tests]`
  - visualizations: `pip install hexy[visual]`
  - and altogether: `pip install hexy[full]`
? 

Thank you, 
Mark

**Comment by RedFT** [comment]
Hello there 😃 

`pip install hexy` will now only install `numpy` as a dependency.

https://github.com/RedFT/Hexy/releases/tag/1.4

Feel free to reopen this issue if it doesn't solve your problem.

**Comment by breznak** [comment]
> pip install hexy will now only install numpy as a dependency. 

thank you!! :100: This is indeed perfect! 
Now we can use hexy without any problem :+1:
